export const todoListsActions = {
  ADD_TODO_LIST: 'ADD_TODO_LIST',
  DELETE_TODO_LIST: 'DELETE_TODO_LIST',
  EDIT_TITLE_NAME: 'EDIT_TITLE_NAME',
  EDIT_TODO_LIST: 'EDIT_TODO_LIST',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
} as const;
